name: lab-testing

on: [push, pull_request]

jobs:
  unit-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.0'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run pytest for unit tests
        run: poetry run pytest tests/unit/
  e2e-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.0'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run pytest for unit tests
        run: poetry run pytest tests/e2e/


  