name: lab-coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.0'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run pytest with coverage
        run: poetry run pytest --cov=app --cov-report=term --cov-fail-under=85 --cov-branch
